elasticsearch:
  hosts:
    - "172.20.65.69:9200"  # elasticsearch-cs
    - "172.20.170.199:9200"   # elasticsearch-data1-cs
    - "172.20.38.176:9200"   # elasticsearch-data2-cs
    - "elasticsearch-lb:9200"  # elasticsearch-lb
  socketTimeout: 60000
  connectionTimeout: 5000
  maxConnTotal: 500
  maxConnPerRoute: 100