elasticsearch:
  hosts:
    - "elasticsearch-cs:9200"  # elasticsearch-cs
    - "elasticsearch-data1-cs:9200"   # elasticsearch-data1-cs
    - "elasticsearch-data2-cs:9200"   # elasticsearch-data2-cs
    - "elasticsearch-lb:9200"  # elasticsearch-lb
  socketTimeout: 60000
  connectionTimeout: 5000
  maxConnTotal: 500
  maxConnPerRoute: 100