elasticsearch:
  hosts:
    - "172.20.207.221:9200"  # elasticsearch-cs
    - "172.20.11.244:9200"   # elasticsearch-data1-cs
    - "172.20.198.240:9200"   # elasticsearch-data2-cs
    - "elasticsearch-lb:9200"  # elasticsearch-lb
  socketTimeout: 60000
  connectionTimeout: 5000
  maxConnTotal: 500
  maxConnPerRoute: 100