elasticsearch:
  hosts:
    - "172.20.20.28:9200"  # elasticsearch-cs
    - "172.20.44.36:9200"   # elasticsearch-data1-cs
    - "172.20.209.190:9200"   # elasticsearch-data2-cs
    - "elasticsearch-lb:9200"  # elasticsearch-lb
  socketTimeout: 60000
  connectionTimeout: 5000
  maxConnTotal: 500
  maxConnPerRoute: 100