apiVersion: v1
kind: Service
metadata:
  name: live-control-external-service-lb  # 이름을 external로 변경
  labels:
    app: live-control-spring
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"  # external LB를 위한 annotation
spec:
  type: LoadBalancer
  selector:
    app: live-control-spring
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888