apiVersion: v1
kind: Service
metadata:
  name: live-control-internal-service
  labels:
    app: live-control-spring
spec:
  type: ClusterIP
  selector:
    app: live-control-spring
  ports:
    - protocol: TCP
      port: 8888              # 내부 서비스 포트
      targetPort: 8888        # Pod 내부 애플리케이션 포트
