apiVersion: v1
kind: Service
metadata:
  name: live-control-internal-service-lb
  labels:
    app: live-control-spring
spec:
  type: LoadBalancer
  selector:
    app: live-control-spring
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
